[colors]
draw_bold_text_with_bright_colors = true

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 9

[font.normal]
family = "Menlo"
style = "Regular"

[scrolling]
history = 100000

[window]
title = "Terminal"

[window.padding]
x = 9
y = 10
